title: Haibin Shao 
logo: /images/qr.png
description: Assistant Professor / Department of Automation / Shanghai Jiao Tong University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
